-- Incluir aqui o script de carga DML e DDL do seu modelo de banco de dados.
CREATE SCHEMA IF NOT EXISTS H2CRUD AUTHORIZATION SA;

CREATE TABLE IF NOT EXISTS H2CRUD.SLCT_LOG (
    NR_USE BIGINT NOT NULL,
    CD_TIP SMALLINT NOT NULL,
    TX_SLCT_LOG VARCHAR(50)
    TS_SLCT_LOG TIMESTAMP NOT NULL,
	CONSTRAINT SLCT_LOG_PK PRIMARY KEY (NR_USE, TS_SLCT_LOG)
);

DELETE H2CRUD.SLCT_LOG;

INSERT INTO H2CRUD.SLCT_LOG (NR_USE, CD_TIP, TX_SLCT_LOG, TS_SLCT_LOG) 
                        VALUES (20230910000010, 1  , 'INSERT DE TESTE 1', CURRENT_TIMESTAMP());
INSERT INTO H2CRUD.SLCT_LOG (NR_USE, CD_TIP, TX_SLCT_LOG, TS_SLCT_LOG) 
                        VALUES (20230910000020, 1 , 'INSERT DE TESTE 2', CURRENT_TIMESTAMP());
INSERT INTO H2CRUD.SLCT_LOG (NR_USE, CD_TIP, TX_SLCT_LOG, TS_SLCT_LOG) 
                        VALUES (20230910000030, 1 , 'INSERT DE TESTE 3', CURRENT_TIMESTAMP());                        